/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cell: typeof import('./src/components/cell/index.vue')['default']
    CellGroup: typeof import('./src/components/cell/CellGroup.vue')['default']
    CreateRepo: typeof import('./src/components/CreateRepo.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageCard: typeof import('./src/components/image-card/index.vue')['default']
    InitRepo: typeof import('./src/components/InitRepo.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSwitch: typeof import("naive-ui")["NSwitch"]
    RepoSetting: typeof import('./src/components/RepoSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/tabbar/Tabbar.vue')['default']
    TabbarItem: typeof import('./src/components/tabbar/TabbarItem.vue')['default']
  }
}
