/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/Layout.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import("naive-ui")["NDropdown"]
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    RepoSettings: typeof import('./src/components/RepoSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1: typeof import('./src/components/lead/Step1.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/Tabbar.vue')['default']
    TabbarItem: typeof import('./src/components/tabbar/TabbarItem.vue')['default']
  }
}
